### ISSUE TITLE
Support for Tailwind CSS v3 ?

### ISSUE THREAD

**Issue by AntoineJOULIA** [jherr/create-mf-app#24]
Do you plan to add the possibility to use Tailwind v3?
I tried to manually update the settings (package.json, tailwind.config.js), but the classes of remote modules do not seem to be interpreted... It only works locally to each module.

Thanks for the awesome work!

**Comment by jherr** [comment]
Can you post up a PR that works-ish? And then I'll see if I can take it from there?

**Comment by AntoineJOULIA** [comment]
OK, I'll try.

**Comment by AntoineJOULIA** [comment]
Hello Jack,
Done !

Best regards,
Antoine

Le ven. 7 janv. 2022 à 17:08, Jack Herrington ***@***.***> a
écrit :

**Comment by matigumma** [comment]
i found this
https://github.com/jrandeniya/federated-types-sample

**Comment by Moh3enDev** [comment]
Any update?

**Comment by jherr** [comment]
IMHO Tailwind 3 is not an ideal match for Module Federation, at least without using a CSS in JS converter like twin macro. The issue is the optimization in Tailwind 3 that aggressively removes any unused classes. That's great for packaged apps. But the point of Module Federation is that part of the code is brought in at runtime. Which means that the optimizer won't know what classes are in that runtime code.
